name: diagflow_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dialog_flowtter: ^0.3.3
  flutter:
    sdk: flutter
  go_router: ^14.2.3
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
    - assets/images/logo.png
    - assets/images/bot.png
    - assets/images/user.png
